name: CoFrance Build

on:
  push:

env:
  BUILD_TYPE: Release

job:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Export Visual Studio configuration
        run: | 
          "C:\Program Files (x86)\Microsoft Visual Studio\Installer\setup.exe" export --config vsconfig.json
          Get-Content vsconfig.json

      